CONTRIBUTING.mdにブランチ戦略を記載する
lgtm-factory/lgtm-factory pull request #29
Opened 2024-08-07 06:40 UTC by kagomen

## 概要
CONTRIBUTING.mdにブランチ戦略を記載する

## 関連イシュー
#12 

## 備考
#### ブランチ戦略としてはGitHub Flowを採用する、としました！
理由は以下の通りです。

- シンプルなフローなためGitHubに慣れてない人でも使いやすいこと
- First Contributions JAでもGitHub Flowを採用しており、開発中特に問題がなかったため

ドキュメントの中でブランチ戦略について詳細に説明することは控え、リンクをしています。

#### ブランチ名のフォーマットについては[色々悩んだ結果](https://github.com/lgtm-factory/lgtm-factory/discussions/14)、`<タイトル>-<イシュー番号>` としました！
コミットメッセージと違ってイシュー番号に`#`がついてないのは、 [GitHub Docs](https://docs.github.com/ja/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names#naming-branches-and-tags)に

> 安全に使用できる文字セット

として`#`が書かれていなかったためです。
また、タイトルとイシュー番号の順番がコミットメッセージと異なっているのも、

> ブランチ名は文字で始める必要があります。

とあったためです。

prefixなしの理由については、自分の、「必要ないなら削りたいの精神」からです😅
もし何か質問や指摘などありましたら、お気軽にお願いします！！🙏

2024-08-07 07:57 UTC, kazzyfrog approved these changes
LGTM🐙🐙🐙

2024-08-07 08:00 UTC, kazzyfrog commented
さっそくPR、ありがとうございます！

自分は、作業中の discussionのスレッドも追っていたので、
一通り問題なく把握しました！！👍

2024-08-07 11:32 UTC, kazzyfrog requested changes

2024-08-07 11:32 UTC, kazzyfrog commented on docs/CONTRIBUTING.md
> +  - `git branch -c ブランチ名`
こちら、ブランチの作成は、以下のコマンドかも、、です！
- `git branch ブランチ名`

もしくは、ブランチを作成し、同時にそのブランチに移動したい場合は、下記が使えます！
- `git switch -c ブランチ名`

2024-08-07 11:32 UTC, kazzyfrog commented on docs/CONTRIBUTING.md
> +  - `git branch -c ブランチ名`
ちなみに、調べたら、
`git branch -c`オプションは、既存のブランチの名前を変更して、コピーを作成するコマンドっぽいです！

> -cと-Cオプションは、-mと-Mとまったく同じセマンティクスを持っていますが、ブランチの名前が変更される代わりに、設定とreflogとともに新しい名前にコピーされます。

[参考](https://git-scm.com/docs/git-branch)

2024-08-07 14:32 UTC, kagomen commented on docs/CONTRIBUTING.md
> +  - `git branch -c ブランチ名`
レビューありがとうございます🌟
コンフリクトの件、調査中に不明点などあったら質問させてもらうかもです！🙏

`git switch -c ブランチ名` ですね……！修正します！

2024-08-09 06:46 UTC, kagomen commented
プルリク再提出しました！
ご確認お願いします！🙏

## 修正内容

- コンフリクトの解消
  - 同じCONTRIBUTING.md内の記述のため、#13 と競合が発生していたので、その解消。

- コマンド内容の修正
  - レビューでご指摘いただいた内容を修正しました！

- #13 の見出しと #12 の見出し
  - 同ファイル内で整合性をとるため、見出しをちょこっとだけ変更しました！

2024-08-09 07:06 UTC, kazzyfrog approved these changes
LGTM👾👾👾

修正３点確認しました！
ありがとうございますー！！🙌

2024-08-09 07:21 UTC, kagomen commented
レビュー後にすみません！
追加で修正を加えたものをアップしました💦
修正に入る前に、一言お知らせすればよかったです！以後気をつけます！🙏💦

以下修正内容です

- コミットメッセージの見出しの修正
  - [自分の修正](https://github.com/lgtm-factory/lgtm-factory/pull/29/commits/1ecf0475e2c8d041390cdb5851339a6b3963c420)が一部しか修正していなかったため、そこを修正しました💦
  - 修正**前**
  ```
  # コミットメッセージについて
  ## フォーマット
  ## Type, Emoji
  ## Issue Number
  ```
  - 修正**後**
  ```
  # コミットメッセージについて
  ## フォーマット
  ### Type, Emoji
  ### Issue Number
  ```
  
- 記載するコマンドを増やして、「ブランチに関するコマンド」というタイトルで、一つのトピックにしました
  - CONTRIBUTING.mdを参照される方のミスを未然に減らすため……！

 
かなり細かい変更内容となってますが、再度確認していただけると幸いです。
お手間をとらせてしまい、すみません！🙏

2024-08-09 07:25 UTC, kazzyfrog commented
全然大丈夫ですよ！
自分も、後から見返してちょこちょこ修正したくなること結構あるので！w

- 見出しの修正
- 「ブランチに関するコマンド」というタイトルで、一つのトピック

こちらも、確認しました！
ありがとうございますー！！👍

2024-08-09 07:51 UTC, kagomen commented
ありがとうございます！🙏
@kazzyfrog さんが共有されていたセルフチェックの記事、読んでみました！
こちら、ちょっと深掘りしてみます……！

2024-08-09 08:43 UTC, siso001 approved these changes

2024-08-09 08:44 UTC, siso001 commented
LGTM！

2024-08-09 12:10 UTC, merged